# Generated by Django 5.2 on 2025-05-19 11:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_blog_post_author_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
